//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningBasic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearningBasic.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] created..
        /// </summary>
        internal static string ArrayOfDimension1Created {
            get {
                return ResourceManager.GetString("ArrayOfDimension1Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}, {1}] created..
        /// </summary>
        internal static string ArrayOfDimension2Created {
            get {
                return ResourceManager.GetString("ArrayOfDimension2Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}, {1}, {2}] created..
        /// </summary>
        internal static string ArrayOfDimension3Created {
            get {
                return ResourceManager.GetString("ArrayOfDimension3Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}, {1}, {2}, {3}] created..
        /// </summary>
        internal static string ArrayOfDimension4Created {
            get {
                return ResourceManager.GetString("ArrayOfDimension4Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC interpreter terminated..
        /// </summary>
        internal static string BasicInterpreterTerminated {
            get {
                return ResourceManager.GetString("BasicInterpreterTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C pressed, program aborted..
        /// </summary>
        internal static string CtrlCPressed {
            get {
                return ResourceManager.GetString("CtrlCPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a program name:.
        /// </summary>
        internal static string InputProgramName {
            get {
                return ResourceManager.GetString("InputProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program successfully completed..
        /// </summary>
        internal static string ProgramCompleted {
            get {
                return ResourceManager.GetString("ProgramCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program with name &apos;{0}&apos; loaded..
        /// </summary>
        internal static string ProgramLoaded {
            get {
                return ResourceManager.GetString("ProgramLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program with name &apos;{0}&apos; saved..
        /// </summary>
        internal static string ProgramSaved {
            get {
                return ResourceManager.GetString("ProgramSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize seed {0} accepted..
        /// </summary>
        internal static string RandomizeSeedAccepted {
            get {
                return ResourceManager.GetString("RandomizeSeedAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} line(s) removed..
        /// </summary>
        internal static string RemoveResult {
            get {
                return ResourceManager.GetString("RemoveResult", resourceCulture);
            }
        }
    }
}
